### ISSUE TITLE
Very new to choco - help with set logs location

### ISSUE THREAD

**Issue by ii-batman** [chocolatey/docs#193]
Hi Everyone, 
Loving the product! just started to use it and will try to incorporate with Azure Image Builder to deploy apps to my VM's.

I am finding an issue setting the log file location - following the doc [url](https://docs.chocolatey.org/en-us/choco/commands/config#examples) and setting the value:
`choco config set log-file c:\temp`
Close PowerShell and open new window > install product and I get this at the end: 
`Chocolatey installed 2/2 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).`
When opening config file I can see:
`<add key="log-file" value="c:\temp" />`
So nothing is written to C:\Temp
Am I doing something wrong here?
Thanks Everyone

**Comment by corbob** [comment]
HI @ii-batman I believe this is because `log-file` is a global argument accepted by all commands, and is not actually a configuration option. The `choco config` command allows you to put anything you want in the configuration file, even if it's not actually a valid configuration option.

To be able to set a default for the log file location doesn't seem an unreasonable request to me. I would recommend looking through the issues on [chocolatey/choco](https://github.com/chocolatey/choco/issues) and open an issue there if there isn't already one.

**Comment by ii-batman** [comment]
@corbob 
No worries, I managed to adapt my script to log into my desired location:
`$Packages = 'googlechrome', 'git', 'notepadplusplus', 'adobereader' 

ForEach ($PackageName in $Packages) {
    $action = choco install $PackageName -y  -force --log-file='C:\buildartifacts\Working\_CS_Apps\Choco_Apps\Choco.log' 
    Write-Host "Customization: Installing Chocolatey Applications - $action"
}

$Installed = choco list --local-only
`
Loving the choco! Makes life so much easier!

**Comment by corbob** [comment]
@ii-batman 
That's great to hear. I'm going to close this issue off as it appears we've answered your question. I would definitely suggest taking a look through the choco issues and if there's not already one for having a configuration option for log file location open an issue there to track that it would be good to add to the configuration.
