### ISSUE TITLE
xref links sometimes do not work without setting front matter

### ISSUE THREAD

**Issue by designxsteph** [chocolatey/docs#50]
Using `xref:extensions` without setting it in the front matter, results in this error:

<img width="802" alt="Screen Shot 2020-11-04 at 7 31 30 AM" src="https://user-images.githubusercontent.com/42750725/98117773-d80f0c00-1e6f-11eb-9e43-ee1ca96b504c.png">

The file being referenced is located at `input/en-us/features/extensions.md`

After adding it in the front matter, it worked as expected.

As a test, I went the home page and changed a link to use `xref:faqs`, which seemed to work, but changing a link to use `xref:why` results in the same error above in the picture.

<img width="791" alt="Screen Shot 2020-11-04 at 7 41 22 AM" src="https://user-images.githubusercontent.com/42750725/98118654-296bcb00-1e71-11eb-98ca-c81d936183a0.png">

Not sure what it's not liking, it seems to be random on whether it's going to like the `xref` or not, but the results are always consistent (it either works every time, or says it can't be found every time).

**Comment by gep13** [comment]
@daveaglick @pascalberger can either of you offer any suggestions as to why setting `XRef` in the frontmatter would be required, when the name of the file otherwise should be unique?

Thanks

**Comment by daveaglick** [comment]
It's because the default calculated xref is based on title, not file name (that's deliberate so that xrefs can persist across file renames and refactorings as long as the title of the document doesn't change). So in this case since the title of the document is a bit longer, the xref should be `[text to link](xref:extend-chocolatey-with-powershell-modules-(extensions))` (though this particular title might be problematic because of the parens, but that's a different potential problem).

You can change the xref behavior too if you'd rather have it based only on file name. The default xref value is a computed setting with a value of `Config.FromDocument(doc => doc.GetTitle().Replace(' ', '-'))`. To change it to something else, add something like this to the bootstrapper which will override the default xref computation:

```csharp
.AddSetting(WebKeys.Xref, Config.FromDocument(doc => doc.Destination.FileNameWithoutExtension.Replace(' ', '-')))
```

**Comment by gep13** [comment]
@daveaglick Ah, good to know! I must have read the docs wrong there, as I thought I read it was based on the name of the file.

Thanks for confirming!

**Comment by pascalberger** [comment]
I would suggest to keep it based on title, since this is one of the big advantages when working with xrefs that you can refactor content and links will still work as long as the xref is the same.

@daveaglick Is it also possible to use an ID in the front-matter for xref?
Something like the following in the front matter:

```
---
uid: guidelines
---
```

And then read that value in the config?

**Comment by daveaglick** [comment]
> this is one of the big advantages when working with xrefs that you can refactor content and links will still work as long as the xref is the same

Exactly - linking via path is a good way to...link via path. The value-add for xrefs is that they're not usually dependent on path or file name.

> Is it also possible to use an ID in the front-matter for xref?

Yep! It's the `Xref` metadata value that sets it. If one is defined in front matter it'll take precedence over the calculated value:

```
---
xref: my-document
---
```

And because it's just another metadata value, you can access it like other metadata values: `doc.GetString("Xref")`.

**Comment by gep13** [comment]
@designxsteph I believe I am right in saying that we can close this one out, as in this case, it was expected that an xref entry would be required.

Let me know if you feel that there is still an issue here.
