### ISSUE TITLE
Some Chocolatey.org links produce a 404 error

### ISSUE THREAD

**Issue by pauby** [chocolatey/docs#87]
When going to chocolatey.org/docs links they don't always redirect properly to docs.chocolatey.org and result in a 404 error (tested with both Firefox and Chromium):

![image](https://user-images.githubusercontent.com/12760779/101334028-3fedb380-386f-11eb-8665-e7a15f91ebe8.png)

The following links have issues:

* https://chocolatey.org/docs/CreatePackages
* https://chocolatey.org/docs/HelpersReference
* https://chocolatey.org/docs/How-To-Deprecate-A-Chocolatey-Package
* https://chocolatey.org/docs/CommandsInstall

**Comment by gep13** [comment]
@pauby can you elaborate on the process that you used when finding these links?  Would be good to try to capture all of them at once.

**Comment by pauby** [comment]
I had them bookmarked as they are common links I use, particularly during moderation.

**Comment by ferventcoder** [comment]
Just to add a bit of color - three of these links are incorrect - I'm not sure how they got found and added to bookmarks. It could have been during a bad transition on the wiki docs at some point during the website changes - those links should be lowercase with dashes between them "create-packages", "helpers-reference", and "commands-install". 

It appears the casing is also causing a problem in the case of "How-To-Deprecate-A-Chocolatey-Package" - we never enforced uppercase/lowercase on these. It appears that matters on the way into Statiq.

**Comment by gep13** [comment]
@ferventcoder this isn't so much a Statiq issue, but rather an GitHub Pages issue.  It is hosted on a Posix machine, so URL's are case sensitive.

**Comment by pauby** [comment]
@ferventcoder 

> Just to add a bit of color - three of these links are incorrect - I'm not sure how they got found and added to bookmarks.

The links have been in regular user (mainly to pass to people during moderation) and they worked up until the changeover to docs.chocolatey.org. I also have those same links in AutoHotkey (so I can use shortcuts) and use them more than I do the Bookmarks.

> It could have been during a bad transition on the wiki docs at some point during the website changes - those links should be lowercase with dashes between them "create-packages", "helpers-reference", and "commands-install".

It could have been the case that they were bookmarked during a bad transition. But they worked all the way until the transition. If I have them bookmarked, it's not unreasonable to expect others to have them too.

**Comment by gep13** [comment]
Currently, the generation of redirects from Statiq only supports the creation of a single, case insensitive , page, which is currently:

https://github.com/chocolatey/docs/blob/gh-pages/docs/how-to-deprecate-a-chocolatey-package.html

So I currently can't (not without manually intervening, and potentially causing problems with cloning onto a Windows machine) change this behaviour, so this link:

https://chocolatey.org/docs/How-To-Deprecate-A-Chocolatey-Package

Will currently no re-direct, but this link:

https://chocolatey.org/docs/how-to-deprecate-a-chocolatey-package

will redirect correctly.

Now I may be able to switch these around, but we can't currently have both.

Where there are examples of URL's that need to be redirected such as:

https://chocolatey.org/docs/CreatePackages

I can add a redirect for those, since there isn't an existing lower case version of a redirect that would cause a collision.

Please let me know how you think we should proceed.

**Comment by pauby** [comment]
Given what @ferventcoder said above, if the uppercase links (How-To-Deprecate-A-Chocolatey-Package as an example) are incorrect, then it would not make sense to replace the correct link (how-to-deprecate-a-chocolatey-package) with it. That would be my suggestion.

Where there are no lowercase versions I'd agree that we should put in place redirects if they don't cause collisions.

**Comment by ferventcoder** [comment]
Agreed with Paul on the above. And if we can custom the 404 to maybe ask folks to try the link with lowercase if it detects they are using uppercase (or get smart somewhere and try to handle this aspect for them and if that doesn't work to lowercase the path, then show them the 404).

**Comment by gep13** [comment]
Going to close this issue out, and continue discussion [here](https://github.com/chocolatey/docs/issues/88).
