### ISSUE TITLE
Incorrect numbering for package triage process

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/docs#97]
These should all be numbered sequentially, 1 through 6:

![image](https://user-images.githubusercontent.com/1271146/102193490-0b53aa80-3eb4-11eb-8aea-83d82e488bda.png)

**Comment by gep13** [comment]
@TheCakeIsNaOH thanks for raising this.

Since this is actually two separate issues, I think we should address them independently.

I have moved the issue from the wiki repository into this repository, and we can use that for tracking changes to the triage process.

This issue I will update to reflect the issue with the numbering on that page.

**Comment by gep13** [comment]
Follow up issue for updating the package triage process is here: https://github.com/chocolatey/docs/pull/98
